### PR TITLE
add tests

### PR DESCRIPTION
**Pull request by marcogrueter**
Hi, sorry, didn't have time to write tests yesterday and you where fast with merging :)
So here is another pull requests with tests for almost any relationship type - except for the many to many polymorphic relation. I'll add that one later on.

I'm am not 100% sure though, if the tests are reasonable and not a bit too constructed.

### CODE REVIEW

**Comment by marcogrueter** [comment]
Oh, and I wasn't quite sure what the difference between "DriverTest" and "EloquentDriverTest" was. I've put everything in "DriverTest" - let me know if you want that changed.

**Comment by nilportugues** [comment]
@marcogrueter yeah I merged fast but first i read your code and ran some tests locally. So no problem. 

I'll review your new commit.
- `EloquentDriver` is the entry point, as I intend to write a set of Drivers (eloquent, doctrine for now) targetting specific classes to serialize.
- Once those classes have been found, the `Driver` class is ran.

**Comment by nilportugues** [comment]
@marcogrueter I'll merge this too. This is great .

**Comment by marcogrueter** [comment]
Cool, glad I could do something useful in return. Your transformer is great!

**Pull request merged**
